# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2337448af4f8cf0345c8e444dd2dcec7922bb4bb4bd56c604061566f00afef0dd2a710f0cb962922598cb639dd664653d2a0a81d6dadd39b5f3683921a3e682b

test:
  secret_key_base: fd79d81e5b38e595fd159bcf751afc33454a338caee09b5451f852cf4578392ae7434b8fbf50cd063117402cdc0e03d727117693548e7ed71de3e3068dbb6e5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
